---
#-------------------------------
# General Site Settings
title: Good Things from Scratch
logo: "/assets/logo.svg" # You can add own logo. For example '/assets/logo.png'.
description: Good Things from Scratch
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goodthingsfromscratch.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Meredith Blair Bearov
  bio: Hi, my name is Meredith Blair Bearov. I’ve spent over 20 years in the world of high-end food and hospitality, doing everything from fine dining and event planning to culinary retail and sales. Along the way, I’ve had the chance to work at some pretty amazing places. These experiences have equipped me with a unique perspective and an understanding of what it takes to plan and execute exceptional experiences.
  image: "/assets/food1.jpg"
  avatar: "/assets/profile-picture1.png"

# Example of adding a new link to the section author - {icon: "ion-logo-github", link: "https://github.com"}
author-social:
  - { icon: "ion-logo-twitter", link: "https://twitter.com" }
  - { icon: "ion-logo-facebook", link: "https://facebook.com" }
  - { icon: "ion-logo-instagram", link: "https://instagram.com" }
  - { icon: "ion-logo-pinterest", link: "https://pinterest.com" }

#-------------------------------
# Hero Settings
hero:
  hero__image: "/assets/food3.jpg"
  hero__title: "Welcome to Good Things from Scratch"
  hero__description: "Palm Desert's Personal Culinary Experiences"

#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
  - { icon: "ion-logo-twitter", link: "https://twitter.com" }
  - { icon: "ion-logo-facebook", link: "https://facebook.com" }
  - { icon: "ion-logo-instagram", link: "https://instagram.com" }
  - { icon: "ion-logo-pinterest", link: "https://pinterest.com" }

#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
# mailchimp:
#   mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# NOTE
# If you don't want to use the subscribe section, just remove or comment out these lines.

#-------------------------------
# Contant form Settings
contact:
  email: mbbearov@gmail.com # Add your email for contant form 
  description: Fill out the form below if you have any questions or would like to book an event. # Add a description of your form

# NOTE
# Mangila comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed
