title: Good Things from Scratch
logo: /assets/logo.svg
description: Good Things from Scratch
baseurl: ""
url: https://goodthingsfromscratch.netlify.app
hero:
  hero__image: /assets/food3.jpg
  hero__title: Good Things from Scratch
  hero__description: |-
    Personal Chef and Boutique Gatherings <br> 
    Coachella Valley
author:
  name: Meredith Bearov
  bio: Hi, my name is Meredith Bearov. I’ve spent over 20 years in the world of high-end food and hospitality, doing everything from fine dining and event planning to culinary retail and sales. Along the way, I’ve had the chance to work at some pretty amazing places. These experiences have equipped me with a unique perspective and an understanding of what it takes to plan and execute exceptional experiences.
  image: /assets/food1.jpg
  avatar: /assets/profile-picture1.png
contact:
  description: I'd love to hear from you. Please fill out the form below if you have any questions or would like to talk about an event.
author-social:
  - icon: ion-logo-instagram
    link: https://instagram.com/goodthingsfromscratch/
  - icon: ion-logo-linkedin
    link: https://linkedin.com/in/meredith-bearov/
google-analytics: null
social:
  - icon: ion-logo-instagram
    link: https://instagram.com/goodthingsfromscratch/
  - icon: ion-logo-linkedin
    link: https://linkedin.com/in/meredith-bearov/
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
paginate: 6
paginate_path: /page/:num
defaults:
  - values:
      permalink: /:basename:output_ext
    scope:
      path: _pages
# Folders to Include
include:
  - _pages
collections:
  reviews:
    output: true
# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
