title: Good Things from Scratch
logo: /assets/logo.svg
description: Good Things from Scratch
baseurl: ""
url: https://goodthingsfromscratch.netlify.app
hero:
  hero__image: /assets/food3.jpg
  hero__title: Welcome to Good Things from Scratch
  hero__description: |-
    Personal Chef and Boutique Gatherings
    In the Coachella Valley
author:
  name: Meredith Bearov
  bio: Hi, my name is Meredith Bearov. I’ve spent over 20 years in the world of high-end food and hospitality, doing everything from fine dining and event planning to culinary retail and sales. Along the way, I’ve had the chance to work at some pretty amazing places. These experiences have equipped me with a unique perspective and an understanding of what it takes to plan and execute exceptional experiences.
  image: /assets/food1.jpg
  avatar: /assets/profile-picture1.png
contact:
  email: mbbearov@gmail.com
  description: I'd love to hear from you. Please fill out the form below if you have any questions or would like to talk about an event.
sitedescription: Sin tantum modo ad indicia veteris memoriae cognoscenda, curiosorum. Haec et tu ita posuisti, et verba vestra sunt. Idemne potest esse dies saepius, qui semel fuit? Ampulla enim sit necne sit, quis non iure optimo irrideatur, si laboret? Ego vero volo in virtute vim esse quam maximam; Serpere anguiculos, nare anaticulas, evolare merulas, cornibus uti videmus boves, nepas aculeis. Archytam? Qua ex cognitione facilior facta est investigatio rerum occultissimarum. Negat enim tenuissimo victu, id est contemptissimis escis et potionibus, minorem voluptatem percipi quam.
google-analytics: null
author-social:
  - link: https://instagram.com
    icon: ion-logo-instagram
  - link: https://linkedin.com
    icon: ion-logo-linkedin
defaults:
  - values:
      permalink: /:basename:output_ext
    scope:
      path: _pages
include:
  - _pages
  - _reviews
collections:
  reviews:
    output: true
social:
  - icon: ion-logo-instagram
    link: https://instagram.com
  - icon: ion-logo-linkedin
    link: https://linkedin.com
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
paginate: 3
paginate_path: /page/:num
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
