title: Good Things from Scratch
logo: /assets/logo.svg
description: Good Things from Scratch
baseurl: ""
url: https://goodthingsfromscratch.netlify.app
hero:
  hero__image: /assets/food3.jpg
  hero__title: Good Things from Scratch
  hero__description: |-
    Personal Chef and Boutique Gatherings <br> 
    Coachella Valley
author:
  name: Meredith Bearov
  bio: Hi, my name is Meredith Bearov. I’ve spent over 20 years in the world of high-end food and hospitality, doing everything from fine dining and event planning to culinary retail and sales. Along the way, I’ve had the chance to work at some pretty amazing places. These experiences have equipped me with a unique perspective and an understanding of what it takes to plan and execute exceptional experiences.
  image: /assets/food1.jpg
  avatar: /assets/profile-picture1.png
contact:
  email: mbbearov@gmail.com
  description: I'd love to hear from you. Please fill out the form below if you have any questions or would like to talk about an event.
sitedescription: |-
  My name is Meredith Bearov. I’ve spent over 20 years in the world of high-end food and hospitality, doing everything from fine dining and event planning to culinary retail and sales. Along the way, I’ve had the chance to work at some pretty amazing places. These experiences have equipped me with a unique perspective and an understanding of what it takes to plan and execute exceptional experiences.
  <br><br>
  I specialize in creating boutique experiences. Whether it’s an intimate gathering or a special celebration, I love working closely with my clients to plan events and design custom menus that reflect their tastes, preferences, and the freshest, in-season ingredients. From the initial consultation to shopping at local farmers markets, to wine selection, to event coordination and planning, I personally curate every detail. 
  <br><br>
  My goal is to give you a personal chef experience, crafting meals tailored to your unique needs, whether it’s something casual or a more formal event. It’s all about creating something meaningful and memorable, where every dish was made just for you.
google-analytics: null
author-social:
  - link: https://instagram.com
    icon: ion-logo-instagram
  - link: https://linkedin.com
    icon: ion-logo-linkedin
defaults:
  - values:
      permalink: /:basename:output_ext
    scope:
      path: _pages
include:
  - _pages
  - _reviews
collections:
  reviews:
    output: true
social:
  - icon: ion-logo-instagram
    link: https://instagram.com
  - icon: ion-logo-linkedin
    link: https://linkedin.com
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
paginate: 3
paginate_path: /page/:num
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
