title: Good Things from Scratch
logo: /assets/logo.svg
description: Good Things from Scratch
baseurl: ""
url: https://goodthingsfromscratch.netlify.app
hero:
  hero__image: /assets/food3.jpg
  hero__title: Welcome to Good Things from Scratch
  hero__description: Personal Culinary Experiences
author:
  name: Meredith Bearov
  bio: Hi, my name is Meredith Bearov. I’ve spent over 20 years in the world of high-end food and hospitality, doing everything from fine dining and event planning to culinary retail and sales. Along the way, I’ve had the chance to work at some pretty amazing places. These experiences have equipped me with a unique perspective and an understanding of what it takes to plan and execute exceptional experiences.
  image: /assets/food1.jpg
  avatar: /assets/profile-picture1.png
contact:
  email: mbbearov@gmail.com
  description: I'd love to hear from you. Please fill out the form below if you have any questions or would like to talk about an event.
author-social:
  - icon: ion-logo-instagram
    link: https://instagram.com
  - icon: ion-logo-linkedin
    link: https://linkedin.com
google-analytics: null
defaults:
  - scope:
      path: _pages
    values:
      permalink: /:basename:output_ext
include:
  - _pages
social:
  - icon: ion-logo-instagram
    link: https://instagram.com
  - icon: ion-logo-linkedin
    link: https://linkedin.com
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
paginate: 9
paginate_path: /page/:num
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
