backend:
  name: github
  repo: stillpoint-software/goodthingsfromscratch 
  branch: main 

media_folder: "assets"

collections:
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Configuration"
        name: "config"
        file: "_config.yml" 
        delete: false
        fields:
          - label: "Site"
            name: "site"
            widget: "object"
            fields:
              - { label: "Site Title", name: "site_title", widget: "string", required: true }
              - { label: "Site Description", name: "site_description", widget: "text", required: true }

          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - { label: "Author Name", name: "name", widget: "string", required: true }
              - { label: "Author Bio", name: "bio", widget: "text", required: true }
              - { label: "Author Image", name: "image", widget: "image", required: true }
              - { label: "Author Avatar", name: "avatar", widget: "image", required: true }

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Image", name: "hero__image", widget: "image", required: true }
              - { label: "Hero Title", name: "hero__title", widget: "string", required: true }
              - { label: "Hero Description", name: "hero__description", widget: "text", required: true }

          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Contact Email", name: "email", widget: "string", required: true }
              - { label: "Contact Description", name: "description", widget: "text", required: true }

  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" 
    folder: "_posts" 
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss", }
      - { label: "Asset", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "string", required: false }
  - name: "pages"
    label: "Pages"
    editor:
      preview: true
    files:
      - label: "About Page"
        name: "about"
        file: "_pages/about.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Perma Link", name: "permalink", widget: "hidden", default: "page" }
          - { label: "Title", name: "title", widget: "hidden", default: "page" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Image Header", name: "image", widget: "image", required: true }
      - label: "Inspiration Page"
        name: "inspiration"
        file: "_pages/inspiration.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Perma Link", name: "permalink", widget: "hidden", default: "page" }
          - { label: "Title", name: "title", widget: "hidden", default: "page" }
          - { label: "Image Header", name: "image", widget: "image", required: true } 
          - label: "Gallery"
            name: "images"
            widget: "list"
            fields:
              - { label: "Asset", name: "path", widget: "image" }
              - { label: "Title", name: "text", widget: "string" }
